kind: Secret
apiVersion: v1
metadata:
  name: mongodb-standalone
  namespace: project-test
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb-standalone
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    app.kubesphere.io/instance: mongodb-standalone
    helm.sh/chart: mongodb-13.15.4
  annotations:
    kubesphere.io/creator: dev-zhao
    meta.helm.sh/release-name: mongodb-standalone
    meta.helm.sh/release-namespace: project-test
data:
  mongodb-root-password: MTIzNDU2
type: Opaque
