kind: ConfigMap
apiVersion: v1
metadata:
  name: ks-devops-agent
  namespace: kubesphere-devops-worker
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: devops
    meta.helm.sh/release-namespace: kubesphere-devops-system
data:
  MavenSetting: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this worwalkmank for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
    -->

    <!--
     | This is the configuration file for Maven. It can be specified at two levels:
     |
     |  1. User Level. This settings.xml file provides configuration for a single user,
     |                 and is normally provided in ${user.home}/.m2/settings.xml.
     |
     |                 NOTE: This location can be overridden with the CLI option:
     |
     |                 -s /path/to/user/settings.xml
     |
     |  2. Global Level. This settings.xml file provides configuration for all Maven
     |                 users on a machine (assuming they're all using the same Maven
     |                 installation). It's normally provided in
     |                 ${maven.conf}/settings.xml.
     |
     |                 NOTE: This location can be overridden with the CLI option:
     |
     |                 -gs /path/to/global/settings.xml
     |
     | The sections in this sample file are intended to give you a running start at
     | getting the most out of your Maven installation. Where appropriate, the default
     | values (values used when the setting is not specified) are provided.
     |
     |-->
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
      <!-- localRepository
       | The path to the local repository maven will use to store artifacts.
       |
       | Default: ${user.home}/.m2/repository
      <localRepository>/path/to/local/repo</localRepository>
      -->

      <!-- interactiveMode
       | This will determine whether maven prompts you when it needs input. If set to false,
       | maven will use a sensible default value, perhaps based on some other setting, for
       | the parameter in question.
       |
       | Default: true
      <interactiveMode>true</interactiveMode>
      -->

      <!-- offline
       | Determines whether maven should attempt to connect to the network when executing a build.
       | This will have an effect on artifact downloads, artifact deployment, and others.
       |
       | Default: false
      <offline>false</offline>
      -->

      <!-- pluginGroups
       | This is a list of additional group identifiers that will be searched when resolving plugins by their prefix, i.e.
       | when invoking a command line like "mvn prefix:goal". Maven will automatically add the group identifiers
       | "org.apache.maven.plugins" and "org.codehaus.mojo" if these are not already contained in the list.
       |-->
      <pluginGroups>
        <!-- pluginGroup
         | Specifies a further group identifier to use for plugin lookup.
        <pluginGroup>com.your.plugins</pluginGroup>
        -->
      </pluginGroups>

      <!-- proxies
       | This is a list of proxies which can be used on this machine to connect to the network.
       | Unless otherwise specified (by system property or command-line switch), the first proxy
       | specification in this list marked as active will be used.
       |-->
      <proxies>
        <!-- proxy
         | Specification for one proxy, to be used in connecting to the network.
         |
        <proxy>
          <id>optional</id>
          <active>true</active>
          <protocol>http</protocol>
          <username>proxyuser</username>
          <password>proxypass</password>
          <host>proxy.host.net</host>
          <port>80</port>
          <nonProxyHosts>local.net|some.host.com</nonProxyHosts>
        </proxy>
        -->
      </proxies>

      <!-- servers
       | This is a list of authentication profiles, keyed by the server-id used within the system.
       | Authentication profiles can be used whenever maven must make a connection to a remote server.
       |-->
      <servers>
        <!-- server
         | Specifies the authentication information to use when connecting to a particular server, identified by
         | a unique name within the system (referred to by the 'id' attribute below).
         |
         | NOTE: You should either specify username/password OR privateKey/passphrase, since these pairings are
         |       used together.
         |
        <server>
          <id>deploymentRepo</id>
          <username>repouser</username>
          <password>repopwd</password>
        </server>
        -->

        <!-- Another sample, using keys to authenticate.
        <server>
          <id>siteServer</id>
          <privateKey>/path/to/private/key</privateKey>
          <passphrase>optional; leave empty if not used.</passphrase>
        </server>
        -->
      </servers>

      <!-- mirrors
       | This is a list of mirrors to be used in downloading artifacts from remote repositories.
       |
       | It works like this: a POM may declare a repository to use in resolving certain artifacts.
       | However, this repository may have problems with heavy traffic at times, so people have mirrored
       | it to several places.
       |
       | That repository definition will have a unique id, so we can create a mirror reference for that
       | repository, to be used as an alternate download site. The mirror site will be the preferred
       | server for that repository.
       |-->
      <mirrors>
          <mirror>
              <id>aliyunmaven</id>
              <mirrorOf>*</mirrorOf>
              <name>阿里云公共仓库</name>
              <url>https://maven.aliyun.com/repository/public</url>
          </mirror>
      </mirrors>

      <!-- profiles
       | This is a list of profiles which can be activated in a variety of ways, and which can modify
       | the build process. Profiles provided in the settings.xml are intended to provide local machine-
       | specific paths and repository locations which allow the build to work in the local environment.
       |
       | For example, if you have an integration testing plugin - like cactus - that needs to know where
       | your Tomcat instance is installed, you can provide a variable here such that the variable is
       | dereferenced during the build process to configure the cactus plugin.
       |
       | As noted above, profiles can be activated in a variety of ways. One way - the activeProfiles
       | section of this document (settings.xml) - will be discussed later. Another way essentially
       | relies on the detection of a system property, either matching a particular value for the property,
       | or merely testing its existence. Profiles can also be activated by JDK version prefix, where a
       | value of '1.4' might activate a profile when the build is executed on a JDK version of '1.4.2_07'.
       | Finally, the list of active profiles can be specified directly from the command line.
       |
       | NOTE: For profiles defined in the settings.xml, you are restricted to specifying only artifact
       |       repositories, plugin repositories, and free-form properties to be used as configuration
       |       variables for plugins in the POM.
       |
       |-->
      <profiles>
        <!-- profile
         | Specifies a set of introductions to the build process, to be activated using one or more of the
         | mechanisms described above. For inheritance purposes, and to activate profiles via <activatedProfiles/>
         | or the command line, profiles have to have an ID that is unique.
         |
         | An encouraged best practice for profile identification is to use a consistent naming convention
         | for profiles, such as 'env-dev', 'env-test', 'env-production', 'user-jdcasey', 'user-brett', etc.
         | This will make it more intuitive to understand what the set of introduced profiles is attempting
         | to accomplish, particularly when you only have a list of profile id's for debug.
         |
         | This profile example uses the JDK version to trigger activation, and provides a JDK-specific repo.
        <profile>
          <id>jdk-1.4</id>

          <activation>
            <jdk>1.4</jdk>
          </activation>

          <repositories>
            <repository>
              <id>jdk14</id>
              <name>Repository for JDK 1.4 builds</name>
              <url>http://www.myhost.com/maven/jdk14</url>
              <layout>default</layout>
              <snapshotPolicy>always</snapshotPolicy>
            </repository>
          </repositories>
        </profile>
        -->

        <!--
         | Here is another profile, activated by the system property 'target-env' with a value of 'dev',
         | which provides a specific path to the Tomcat instance. To use this, your plugin configuration
         | might hypothetically look like:
         |
         | ...
         | <plugin>
         |   <groupId>org.myco.myplugins</groupId>
         |   <artifactId>myplugin</artifactId>
         |
         |   <configuration>
         |     <tomcatLocation>${tomcatPath}</tomcatLocation>
         |   </configuration>
         | </plugin>
         | ...
         |
         | NOTE: If you just wanted to inject this configuration whenever someone set 'target-env' to
         |       anything, you could just leave off the <value/> inside the activation-property.
         |
        <profile>
          <id>env-dev</id>

          <activation>
            <property>
              <name>target-env</name>
              <value>dev</value>
            </property>
          </activation>

          <properties>
            <tomcatPath>/path/to/tomcat/instance</tomcatPath>
          </properties>
        </profile>
        -->
      </profiles>

      <!-- activeProfiles
       | List of profiles that are active for all builds.
       |
      <activeProfiles>
        <activeProfile>alwaysActiveProfile</activeProfile>
        <activeProfile>anotherAlwaysActiveProfile</activeProfile>
      </activeProfiles>
      -->
    </settings>
  PodmanSetting: >
    # For more information on this configuration file, see
    containers-registries.conf(5).

    #

    # NOTE: RISK OF USING UNQUALIFIED IMAGE NAMES

    # We recommend always using fully qualified image names including the
    registry

    # server (full dns name), namespace, image name, and tag

    # (e.g., registry.redhat.io/ubi8/ubi:latest). Pulling by digest (i.e.,

    # quay.io/repository/name@digest) further eliminates the ambiguity of tags.

    # When using short names, there is always an inherent risk that the image
    being

    # pulled could be spoofed. For example, a user wants to pull an image named

    # `foobar` from a registry and expects it to come from myregistry.com. If

    # myregistry.com is not first in the search list, an attacker could place a

    # different `foobar` image at a registry earlier in the search list. The
    user

    # would accidentally pull and run the attacker's image and code rather than
    the

    # intended content. We recommend only adding registries which are completely

    # trusted (i.e., registries which don't allow unknown or anonymous users to

    # create accounts with arbitrary names). This will prevent an image from
    being

    # spoofed, squatted or otherwise made insecure.  If it is necessary to use
    one

    # of these registries, it should be added at the end of the list.

    #

    # # An array of host[:port] registries to try when pulling an unqualified
    image, in order.

    # unqualified-search-registries = ["example.com"]

    #

    # [[registry]]

    # # The "prefix" field is used to choose the relevant [[registry]] TOML
    table;

    # # (only) the TOML table with the longest match for the input image name

    # # (taking into account namespace/repo/tag/digest separators) is used.

    # # 

    # # The prefix can also be of the form: *.example.com for wildcard subdomain

    # # matching.

    # #

    # # If the prefix field is missing, it defaults to be the same as the
    "location" field.

    # prefix = "example.com/foo"

    #

    # # If true, unencrypted HTTP as well as TLS connections with untrusted

    # # certificates are allowed.

    # insecure = false

    #

    # # If true, pulling images with matching names is forbidden.

    # blocked = false

    #

    # # The physical location of the "prefix"-rooted namespace.

    # #

    # # By default, this is equal to "prefix" (in which case "prefix" can be
    omitted

    # # and the [[registry]] TOML table can only specify "location").

    # #

    # # Example: Given

    # #   prefix = "example.com/foo"

    # #   location = "internal-registry-for-example.net/bar"

    # # requests for the image example.com/foo/myimage:latest will actually work
    with the

    # # internal-registry-for-example.net/bar/myimage:latest image.

    #

    # # The location can be empty iff prefix is in a

    # # wildcarded format: "*.example.com". In this case, the input reference
    will

    # # be used as-is without any rewrite.

    # location = internal-registry-for-example.com/bar"

    #

    # # (Possibly-partial) mirrors for the "prefix"-rooted namespace.

    # #

    # # The mirrors are attempted in the specified order; the first one that can
    be

    # # contacted and contains the image will be used (and if none of the
    mirrors contains the image,

    # # the primary location specified by the "registry.location" field, or
    using the unmodified

    # # user-specified reference, is tried last).

    # #

    # # Each TOML table in the "mirror" array can contain the following fields,
    with the same semantics

    # # as if specified in the [[registry]] TOML table directly:

    # # - location

    # # - insecure

    # [[registry.mirror]]

    # location = "example-mirror-0.local/mirror-for-foo"

    # [[registry.mirror]]

    # location = "example-mirror-1.local/mirrors/foo"

    # insecure = true

    # # Given the above, a pull of example.com/foo/image:latest will try:

    # # 1. example-mirror-0.local/mirror-for-foo/image:latest

    # # 2. example-mirror-1.local/mirrors/foo/image:latest

    # # 3. internal-registry-for-example.net/bar/image:latest

    # # in order, and use the first one that exists.


    unqualified-search-registries = ["docker.io"]


    [[registry]]

    prefix = "docker.io"

    location = "jkzyghm3.mirror.aliyuncs.com"

    insecure = true


    [[registry]]

    prefix = "192.168.0.112:30002"

    location = "192.168.0.112:30002"

    insecure = true